In [1]:
# x : numpy 1-D input array.

# N : int,Number of columns in the output. If N is not specified, a square array is returned (N = len(x)).

# output- Van der Monde matrix of order N. The first column is x^(N-1), the second x^(N-2) and so forth.
# example:
import numpy as np
x=np.array([1,2,3,4])
N=3
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [2]:
#CHnaging number of required coloumns(N)

import numpy as np
x=np.array([1,2,3,4])
N=4
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]], dtype=int32)

In [4]:
#Not specifying number of required coloumns(N)

import numpy as np
x=np.array([1,2,3])
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1]], dtype=int32)